### ISSUE TITLE
Q: Does it support dynamic custom variables?

### ISSUE THREAD

**Issue by madorin** [mossadal/math-parser#1]
We have expressions that may use some of from a lot of variables, more than 10K.
Does your parser have something like onVariable or onFunction events to catch and provide custom variables?

**Comment by mossadal** [comment]
What you can do is write a custom `Interpreter`. Have a look at the standard `Evaluator` that is shipped with the library. You probably want to write your own `Lexer` too, allowing for more general variable names, and possibly to turn off implicit multiplication.

**Comment by k00ni** [comment]
I am also in need of something like that. Can you give us a hint how to realize that (maybe with a custom `Interpreter`)? That would be helpful as a starting point. 

I have expressions like `foobar + 1` to parse. My current **workaround** is automatically replacing all custom variables with a letter from a-z (except `e`, because its reserved) before giving it to `StdMathParser`. But that limits the total amount to 25 variables.

Any feedback is appreciated. Thanks in advance.

**Comment by f1mishutka** [comment]
> I have expressions like `foobar + 1` to parse.

I'm looking for a way to use multicharacter variable names too.

Trying to disable Implicit Multiplication and it does not work:
```
class MyCustomStdMathParser extends StdMathParser {
  protected static function allowImplicitMultiplication()  {
    return false;
  }
}
```

Could someone please to point me in right direction?

How can I parse expression like '5 * yoho' providing value for 'yoho' variable?

Thank you.

**Comment by mossadal** [comment]
Turning off implicit multiplication is a good start.

If you want to support multi character variable names, you also need a custom Lexer.

Create a lexer by copying StdMathLexer and change 

```
        $this->add(new TokenDefinition('/[a-zA-Z]/', TokenType::Identifier));
```

to something like

```
        $this->add(new TokenDefinition('/[a-zA-Z]+/', TokenType::Identifier));
```

(depending on what kind of variable names you want to support). I haven't tested this, but I don't see why it shouldn't work. Let me know if you need more details.

**Comment by madorin** [comment]
FYI, I ended up by developing Matex project, that supports custom variables and functions, including dynamic binding.
